# nome del servizio
spring.application.name=eureka-server

# porta su cui gira Eureka
server.port=8761

# queste due righe dicono a Eureka di NON registrare se stesso
# (di default si registrerebbe come client)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
