spring.application.name=servizio-utenti
server.port=8081

spring.datasource.url=jdbc:h2:mem:utentidb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# path corretto per Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# fix per il 404 — disabilita il fetch iniziale che fallisce
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# fix compatibilità
eureka.instance.prefer-ip-address=true